-- 0008_storage_policies.sql
-- Scope (Spec V1 §11): private buckets + object-path policies/functions.
-- Acceptance: cross-user path tests fail closed.
--
-- Spec §12.1:
--   * Buckets are PRIVATE: dog-avatars, behavior-raw, digestive-raw, food-labels, exports.
--   * Object key is generated by the API, never the client:
--       users/{uid}/dogs/{dog_id}/{domain}/{event_id}/{uuid}.{ext}
--   * Mobile gets a signed upload URL for exactly one path with short expiry.
--   * No public URL for raw behavioral video.

-- ---------------------------------------------------------------------------
-- Private buckets (idempotent)
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values
  ('dog-avatars',  'dog-avatars',  false),
  ('behavior-raw', 'behavior-raw', false),
  ('digestive-raw','digestive-raw',false),
  ('food-labels',  'food-labels',  false),
  ('exports',      'exports',      false)
on conflict (id) do update set public = excluded.public;

-- ---------------------------------------------------------------------------
-- Path helpers
-- ---------------------------------------------------------------------------
-- Owner uuid encoded as the second path segment: users/{uid}/...
-- Returns NULL for any path not under users/{valid-uuid}/ — NULL never matches
-- auth.uid(), so malformed paths fail closed.
create or replace function public.storage_object_owner(object_name text)
returns uuid
language sql
immutable
as $$
  select case
           when (storage.foldername(object_name))[1] = 'users'
             then nullif((storage.foldername(object_name))[2], '')::uuid
           else null
         end;
$$;

comment on function public.storage_object_owner(text) is
  'Extracts owner uid from users/{uid}/... object paths. NULL (fail closed) otherwise.';

-- Canonical media path shape (Spec §12.1):
--   users/{uid}/dogs/{dog_id}/{domain}/{event_id}/{uuid}.{ext}
-- storage.foldername() drops the filename, so a canonical media object has exactly
-- 6 folder segments. dog-avatars and exports use the same users/{uid}/... prefix but
-- are not bound to the full 6-segment media shape (avatars: users/{uid}/dogs/{dog_id}/avatar/...).
create or replace function public.is_canonical_media_path(object_name text)
returns boolean
language sql
immutable
as $$
  select (storage.foldername(object_name))[1] = 'users'
     and nullif((storage.foldername(object_name))[2], '') is not null
     and (storage.foldername(object_name))[3] = 'dogs'
     and nullif((storage.foldername(object_name))[4], '') is not null
     and (storage.foldername(object_name))[5] in ('behavior', 'digestive', 'food-label')
     and nullif((storage.foldername(object_name))[6], '') is not null
     and cardinality(storage.foldername(object_name)) = 6;
$$;

comment on function public.is_canonical_media_path(text) is
  'True only for API-generated media paths users/{uid}/dogs/{dog_id}/{domain}/{event_id}/{file}.';

-- ---------------------------------------------------------------------------
-- Policies on storage.objects — one policy set per bucket, fail closed.
-- Authorization rule for every operation: the path must belong to the caller
-- (second segment = auth.uid()). Cross-user access is impossible even with a
-- guessed object key (Spec §24.1 signed-URL misuse / path attack controls).
-- ---------------------------------------------------------------------------

-- behavior-raw (raw behavioral video): canonical media path required on write.
create policy behavior_raw_select_own on storage.objects
  for select to authenticated
  using (bucket_id = 'behavior-raw' and public.storage_object_owner(name) = auth.uid());

create policy behavior_raw_insert_own on storage.objects
  for insert to authenticated
  with check (bucket_id = 'behavior-raw'
              and public.storage_object_owner(name) = auth.uid()
              and public.is_canonical_media_path(name));

create policy behavior_raw_update_own on storage.objects
  for update to authenticated
  using (bucket_id = 'behavior-raw' and public.storage_object_owner(name) = auth.uid())
  with check (bucket_id = 'behavior-raw'
              and public.storage_object_owner(name) = auth.uid()
              and public.is_canonical_media_path(name));

create policy behavior_raw_delete_own on storage.objects
  for delete to authenticated
  using (bucket_id = 'behavior-raw' and public.storage_object_owner(name) = auth.uid());

-- digestive-raw (stool photos): canonical media path required on write.
create policy digestive_raw_select_own on storage.objects
  for select to authenticated
  using (bucket_id = 'digestive-raw' and public.storage_object_owner(name) = auth.uid());

create policy digestive_raw_insert_own on storage.objects
  for insert to authenticated
  with check (bucket_id = 'digestive-raw'
              and public.storage_object_owner(name) = auth.uid()
              and public.is_canonical_media_path(name));

create policy digestive_raw_update_own on storage.objects
  for update to authenticated
  using (bucket_id = 'digestive-raw' and public.storage_object_owner(name) = auth.uid())
  with check (bucket_id = 'digestive-raw'
              and public.storage_object_owner(name) = auth.uid()
              and public.is_canonical_media_path(name));

create policy digestive_raw_delete_own on storage.objects
  for delete to authenticated
  using (bucket_id = 'digestive-raw' and public.storage_object_owner(name) = auth.uid());

-- food-labels (label scans): canonical media path required on write.
create policy food_labels_select_own on storage.objects
  for select to authenticated
  using (bucket_id = 'food-labels' and public.storage_object_owner(name) = auth.uid());

create policy food_labels_insert_own on storage.objects
  for insert to authenticated
  with check (bucket_id = 'food-labels'
              and public.storage_object_owner(name) = auth.uid()
              and public.is_canonical_media_path(name));

create policy food_labels_update_own on storage.objects
  for update to authenticated
  using (bucket_id = 'food-labels' and public.storage_object_owner(name) = auth.uid())
  with check (bucket_id = 'food-labels'
              and public.storage_object_owner(name) = auth.uid()
              and public.is_canonical_media_path(name));

create policy food_labels_delete_own on storage.objects
  for delete to authenticated
  using (bucket_id = 'food-labels' and public.storage_object_owner(name) = auth.uid());

-- dog-avatars: users/{uid}/dogs/{dog_id}/... prefix, media-shape check not required
-- (avatars are not domain/event-scoped).
create policy dog_avatars_select_own on storage.objects
  for select to authenticated
  using (bucket_id = 'dog-avatars' and public.storage_object_owner(name) = auth.uid());

create policy dog_avatars_insert_own on storage.objects
  for insert to authenticated
  with check (bucket_id = 'dog-avatars'
              and public.storage_object_owner(name) = auth.uid()
              and (storage.foldername(name))[3] = 'dogs');

create policy dog_avatars_update_own on storage.objects
  for update to authenticated
  using (bucket_id = 'dog-avatars' and public.storage_object_owner(name) = auth.uid())
  with check (bucket_id = 'dog-avatars'
              and public.storage_object_owner(name) = auth.uid()
              and (storage.foldername(name))[3] = 'dogs');

create policy dog_avatars_delete_own on storage.objects
  for delete to authenticated
  using (bucket_id = 'dog-avatars' and public.storage_object_owner(name) = auth.uid());

-- exports: user download artifacts with expiry. Objects are written by the backend
-- (service role bypasses RLS); authenticated users may only READ their own exports
-- through server-generated signed read URLs.
create policy exports_select_own on storage.objects
  for select to authenticated
  using (bucket_id = 'exports' and public.storage_object_owner(name) = auth.uid());

-- No insert/update/delete policy for authenticated on exports = writes fail closed.

-- Helpers are pure lookups; allow the API to use them, but object access stays
-- governed by the policies above.
grant execute on function public.storage_object_owner(text) to authenticated, service_role;
grant execute on function public.is_canonical_media_path(text) to authenticated, service_role;
revoke all on function public.storage_object_owner(text) from anon;
revoke all on function public.is_canonical_media_path(text) from anon;
