"""Supabase Storage adapter (private buckets, server-minted signed URLs)."""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from typing import Any
from urllib.parse import quote

import httpx

from app.config import Settings


class SupabaseStorageProvider:
    """Signed upload/read via Supabase Storage REST API using the service role.

    Object keys are always server-generated by the domain layer; this adapter
    never accepts a client-chosen bucket/key for authorization decisions.
    """

    def __init__(self, settings: Settings, client: httpx.AsyncClient | None = None) -> None:
        if not settings.supabase_url or not settings.supabase_service_role_key:
            raise ValueError("SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are required for supabase storage")
        self._base = settings.supabase_url.rstrip("/")
        self._key = settings.supabase_service_role_key
        self._client = client or httpx.AsyncClient(timeout=30.0)
        self._owns = client is None

    def _headers(self) -> dict[str, str]:
        headers = {"apikey": self._key}
        # Legacy service_role keys are JWTs and may be sent as Bearer tokens.
        # New `sb_secret_...` keys authenticate through the apikey header only.
        if not self._key.startswith("sb_secret_"):
            headers["Authorization"] = f"Bearer {self._key}"
        return headers

    async def create_signed_upload_url(
        self, *, bucket: str, path: str, content_type: str, ttl_seconds: int
    ) -> tuple[str, Any]:
        # Supabase signed upload: POST /storage/v1/object/upload/sign/{bucket}/{path}
        url = f"{self._base}/storage/v1/object/upload/sign/{bucket}/{quote(path, safe='/')}"
        response = await self._client.post(
            url,
            headers={**self._headers(), "Content-Type": "application/json"},
            json={"expiresIn": ttl_seconds},
        )
        response.raise_for_status()
        data = response.json()
        signed_value = data.get("signedURL") or data.get("signedUrl") or data.get("url")
        token = data.get("token")
        if signed_value:
            value = str(signed_value)
            if value.startswith("http"):
                signed = value
            elif value.startswith("/storage/v1/"):
                signed = f"{self._base}{value}"
            else:
                signed = f"{self._base}/storage/v1/{value.lstrip('/')}"
        elif token:
            signed = (
                f"{self._base}/storage/v1/object/upload/sign/{bucket}/"
                f"{quote(path, safe='/')}?token={token}"
            )
        else:
            raise RuntimeError("Supabase signed upload response missing URL/token")
        expires_at = datetime.now(UTC) + timedelta(seconds=ttl_seconds)
        return signed, expires_at

    async def object_exists(self, *, bucket: str, path: str, expected_bytes: int | None = None) -> bool:
        url = f"{self._base}/storage/v1/object/info/{bucket}/{quote(path, safe='/')}"
        response = await self._client.get(url, headers=self._headers())
        if response.status_code == 404:
            return False
        response.raise_for_status()
        if expected_bytes is None:
            return True
        info = response.json()
        size = info.get("metadata", {}).get("size") or info.get("contentLength") or info.get("size")
        if size is None:
            return True
        return int(size) == int(expected_bytes)

    async def delete_object(self, *, bucket: str, path: str) -> None:
        url = f"{self._base}/storage/v1/object/{bucket}/{quote(path, safe='/')}"
        response = await self._client.delete(url, headers=self._headers())
        if response.status_code not in (200, 404):
            response.raise_for_status()

    async def upload_bytes(self, *, bucket: str, path: str, data: bytes, content_type: str) -> None:
        url = f"{self._base}/storage/v1/object/{bucket}/{quote(path, safe='/')}"
        response = await self._client.post(
            url,
            headers={**self._headers(), "Content-Type": content_type, "x-upsert": "true"},
            content=data,
        )
        response.raise_for_status()

    async def create_signed_read_url(self, *, bucket: str, path: str, ttl_seconds: int) -> str:
        url = f"{self._base}/storage/v1/object/sign/{bucket}/{quote(path, safe='/')}"
        response = await self._client.post(
            url,
            headers={**self._headers(), "Content-Type": "application/json"},
            json={"expiresIn": ttl_seconds},
        )
        response.raise_for_status()
        data = response.json()
        signed = data.get("signedURL") or data.get("signedUrl")
        if not signed:
            raise RuntimeError("Supabase signed read response missing URL")
        if str(signed).startswith("http"):
            return str(signed)
        return f"{self._base}/storage/v1{signed}"

    async def aclose(self) -> None:
        if self._owns:
            await self._client.aclose()
